.prettierrc

add: prettier 추가

---

.prettierrc

fix: prettier수정

---

src/_components/feed/FeedCard.tsx
src/app/(pages)/feeds/types/Feed.ts
src/app/(test)/feed-test/page.tsx

후기 카드 공통 컴포넌트 입니다.
- 데이터가 없어서 더미 데이터로 적용 (type 포함)
- props의 타입 설정하여 main, default로 조건 처리
- 이후 작업은 윤지님이 진행하시면 됩니다.
- 없습니다.

후기 카드 default type 1차 적용

---

src/app/(pages)/meets/[meetId]/page.tsx
src/app/(pages)/meets/actions/meetAttendAction.ts
src/app/(pages)/meets/actions/meetDetailAction.ts
src/app/(pages)/meets/components/meetsDetail/MeetIntroSection.tsx
src/app/(pages)/meets/hooks/useMeetCreatorForm.ts
src/app/(pages)/meets/hooks/useMeetDetailController.ts
src/app/(pages)/meets/utils/validateMeetAttendee.ts
src/app/ctest/page.tsx

> 내가 같은 기간에 이미 다른 모임에 참여중인지 확인하여 신청, 작성, 수정 등이 불가능하도록 처리
- meet_attendee 패칭 함수 생성 (`byUserId`, `byMeetId`)
- 내가 같은 기간에 이미 다른 모임에 참여중인지 확인하는 함수 생성 (`checkMeetPostSchedule`, `checkAttendeeSchedule`)
- 같은 기간에 이미 다른 모임에 참여중인 경우 신청, 작성, 수정 불가능하도록 처리

모임 작성, 신청 시 유효성 검사

---

src/_utils/supabase/middleware.ts
src/app/(pages)/meets/[meetId]/page.tsx
src/app/(pages)/meets/actions/meetDetailAction.ts
src/app/(pages)/meets/edit/[meetId]/page.tsx
src/app/(pages)/meets/hooks/useMeetCreatorForm.ts
src/app/(pages)/meets/utils/processSubmitData.ts
src/middleware.ts

> 모임 작성, 수정 페이지에 대한 미들웨어 처리
- 비 로그인 유저 작성, 수정페이지 접근 차단
- 수정 페이지 접근 시 이상한 없는 `meetId` 로 직접 들어올 경우 에러나는데, 이럴 경우 메인으로 돌려보냄
- 수정 페이지에 접근 권한이 없는 유저의 경우 메인으로 돌려보냄 (내가 작성한 글이 아닌 경우 수정페이지 접근 불가능)
middleware를 두 개의 파일에서 진행한 이유가 궁금함니당

모임 관련 미들웨어 처리

---

src/app/(pages)/(auth)/sign-in/page.tsx

> feat: 로그인 리팩토링
- feat: 로그인 리팩토링, url 배포환경에서도 정상 동작 할 수 있게 상수화

feat: 로그인 리팩토링, url 배포환경에서도 정상 동작 할 수 있게 상수화

---

src/_components/calendar/Calendar.tsx
src/app/(pages)/meets/components/meetsDetail/MeetDetailController.tsx
src/app/(pages)/meets/components/meetsDetail/MeetTitleSection.tsx
src/app/(pages)/meets/hooks/useMeetDetailController.ts

> 모임 참여 상태에 따라 모임 톡 버튼 활/비활성화
- 버튼 활성화만 해두었습니다. (css 및 disable 처리)
- 이후 feat/chat-attendee 브랜치에서 함수 연결, chat 데이터 삽입 등 진행 예정

모임 참여시 (작성 포함) 모임 톡 버튼 활성화

---

src/_components/camp/CampDetail.tsx
src/_components/weather/FutureWeather.tsx
src/app/(pages)/meets/components/meetsDetail/MeetDetailController.tsx

fix: 빌드 오류 수정 / 날씨

---

src/_components/common/WriteButton.tsx
src/app/(pages)/meets/components/meetsWrite/meetCreatorSection/MeetCreatorInfoSection.tsx
src/app/(pages)/sos/components/sos/SosCard.tsx
src/app/(pages)/sos/components/sosCreator/SosCreatorForm.tsx
src/app/(pages)/sos/components/sosCreator/formSection/SosCreatorContentSection.tsx
src/app/(pages)/sos/components/sosCreator/formSection/SosCreatorInfoSection.tsx
src/app/(pages)/sos/components/sosCreator/formSection/SosCreatorSearchSection.tsx
src/app/(pages)/sos/components/sosCreator/formSection/SosCreatorTagSection.tsx
src/app/(pages)/sos/components/sosCreator/formSection/SosCreatorTypeSection.tsx
src/app/(pages)/sos/components/sosDetail/SosDetailController.tsx
src/app/(pages)/sos/components/sosDetail/section/SosTitleSection.tsx
src/app/(pages)/sos/components/sosDetail/section/SosUserSection.tsx
src/app/(pages)/sos/page.tsx

> SOS 페이지 스타일 작업
- 작업 중 에러 노출되어 확인을 위해 PR 올렸습니다.

[style/all] SOS 페이지 스타일 1차 작업 PR

---

database.types.ts
src/_components/chat/hooks/useChatSosMessage.ts
src/_components/chat/service/chatService.ts
src/_utils/supabase/supabase.rpc.ts
src/app/(pages)/meets/actions/meetAttendAction.ts
src/app/(pages)/meets/actions/meetWriteAction.ts
src/app/(pages)/sos/components/sosDetail/SosDetailController.tsx
src/app/(pages)/sos/components/sosDetail/section/SosChatSection.tsx

[#86] - sos 상세에서 채팅 적용 안됨 외 1
- sos 상세에서 채팅 버그 해결
- 모임 등록 후 리스트에서 새로고침 해야 데이터 반영됨 (제 코드에서는 문제가 안생겨 우선 push하겠습니ㅏㄷ)(

[Fix/SOS] [#86] - sos 상세에서 채팅 적용 안됨 외 1

---

src/_components/camp/CampReviewSlide.tsx
src/_components/modal/ReviewWriteModal.tsx

> [TanStack Query] 를 이용한 리뷰 불러오기 기능 추가

[Feat/review2] 리뷰 불러오기 기능 추가

---

src/_components/bookmark/BookmarkList.tsx

fix: 로그인한 회원 정보 기준 북마크 리스트 불러오기 수정

---

database.types.ts
src/_components/calendar/Calendar.tsx
src/_components/calendar/CalendarTable.tsx
src/_components/calendar/action/calendarAction.ts
src/_components/camp/CampDetail.tsx
src/_components/modal/ReviewWriteModal.tsx
src/_components/review/ReviewSlideCard.tsx
src/_utils/service/followService.ts
src/app/(pages)/meets/actions/meetWriteAction.ts
src/app/(pages)/mypage/CampingReviews.tsx
src/app/(pages)/sos/components/sosDetail/section/SosChatSection.tsx
src/app/(pages)/sos/components/sosDetail/section/SosTagSection.tsx
src/app/(pages)/sos/hooks/useSosCreatorForm.ts
src/app/(test)/slide-test/page.tsx

feat: 리뷰 모달창 이미지 첨부 기능 추가

---

src/_components/layout/header/Header.tsx
src/_utils/reactQuery/queryKey.keys.ts
src/app/(pages)/sos/service/sosSerivce.ts

[Feat/sos] 활성화 된 sos가 있는 경우 헤더에 표시

---

src/_components/camp/CampDetail.tsx

fix: 후기 개수 및 별점 평점 코드 수정

---

src/_components/camp/CampCard.tsx
src/_components/camp/ReviewBookMarkCount.tsx
src/_components/main/MainReviews.tsx
src/_components/review/ReviewCard.tsx
src/_components/review/ReviewSlideCard.tsx
src/_components/search/ResentSearch.tsx
src/app/(pages)/camp-detail/components/DetailMap.tsx
src/app/(pages)/camp-detail/hooks/useCampDetilMap.ts
src/app/(pages)/mypage/CampingReviews.tsx
src/app/(pages)/search/components/CampCard.tsx
src/app/(pages)/search/components/SearchList.tsx
src/app/(pages)/search/components/SearchResults.tsx
src/app/(pages)/search/hooks/useSearchMap.ts
src/type/map.ts

- 마커 클릭 시 해당하는 인포윈도우 객체 토글 기능 추가
- 검색 결과가 여러 개일 경우, 첫 번째 검색된 캠핑장의 마커로 자동 이동하도록 설정
- map 타입 추가 및 미사용 map 함수 제거하여 코드 정리
- 최근 검색어 링크 연결 useRouter로 링크 연결
- 리뷰카드를 사용하는 모든 곳에 cursor-pointer 클래스 추가
- 디테일 페이지에 인포윈도우 스타일 수정

[Fix/dev] 마커 관련 기능 개선 및 UI/UX 수정

---

src/_utils/supabase/middleware.ts

[fix-dev]  사용하는 미들웨어 주석 제거

---

src/_utils/supabase/middleware.ts

fix: 미들웨어 수정

---

src/_components/layout/header/Header.tsx
src/_components/main/MainIcons.tsx
src/_components/main/MainReviews.tsx
src/_components/main/MainSearch.tsx
src/_components/main/MainSection.tsx
src/app/page.tsx

> 모바일 사이즈 전체적인 폰트 사이즈, 간격 수정
- 모바일 메인, 헤더 사이즈 간격 수정
- 헤더 태그 사이즈
- 레이아웃 간격
- 아이콘 gap 간격
- 전체적인 font-size 수정
- 없습니다.
- 없습니다.

[style/all] 모바일 사이즈 전체적인 폰트 사이즈, 간격 수정

---

src/_components/calendar/CalendarCell.tsx
src/_components/calendar/action/calendarAction.ts
src/_components/calendar/utils/calenderService.ts
src/_components/follower/FollowButton.tsx
src/_components/follower/FollowCard.tsx
src/_components/layout/header/HeaderAuth.tsx
src/_components/main/MainReviews.tsx
src/_components/modal/ReviewWriteModal.tsx
src/_components/weather/FutureWeather.tsx
src/_hooks/search/useRecentSearches.ts
src/_utils/service/followService.ts
src/_utils/supabase/middleware.ts
src/app/(pages)/(auth)/sign-in/page.tsx
src/app/(pages)/meets/[meetId]/page.tsx
src/app/(pages)/meets/components/meetsWrite/MeetCreatorForm.tsx
src/app/(pages)/meets/hooks/useMeetCreatorForm.ts
src/app/(pages)/meets/utils/convertMeetDataToMeetCard.ts
src/app/(pages)/mypage/MeetList.tsx
src/app/(pages)/mypage/hooks/useCalendar.ts

> 사용안하는 주석 제거, 미들웨어 refresh로 수정

Fix/dev 지영

---

src/_components/chat/hooks/useChatSosMessage.ts

sos 채팅 메시지 하나도 없는 경우 발생하는 에러 처리
- sos 채팅 메시지 하나도 없는 경우 발생하는 에러 처리

[Fix/dev] sos 채팅 메시지 하나도 없는 경우 발생하는 에러 처리

---

src/_components/camp/CampDetail.tsx
src/_components/camp/CampReviewSlide.tsx
src/app/(pages)/meets/components/meetsDetail/MeetContentSection.tsx

> 모임 상세 유저 카드 적용 및 캠핑장 상세 리뷰 데이터 조건 처리 및 스타일 수정
- 캠핑장 리뷰 없을 때 ui 처리 
- 모임 상세 유저 카드 데이터 적용
- 스타일 수정
- 없습니다.
- 없습니다.

[style/all] 모임 상세 유저 카드 적용 및 캠핑장 상세 리뷰 데이터 조건 처리 및 스타일 수정

---

src/_components/review/ReviewSlideCard.tsx
src/_hooks/search/useSearchResults.tsx
src/app/(pages)/mypage/UserCard.tsx
src/app/(pages)/search/components/CampCard.tsx

fix: 짜잘이 오류 수정

---

src/_components/chat/ChatListCard.tsx
src/_components/chat/hooks/useChatList.ts
src/_components/chat/hooks/useChatRoom.ts
src/_components/chat/hooks/useChatSosMessage.ts
src/_utils/api/apiKey.ts
src/app/(pages)/chat/page.tsx
src/app/(pages)/sos/components/sos/SosList.tsx

[Hotfix] - UT이후 수정사항 main에 반영
